// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://suriubspgymcogfqnabm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1cml1YnNwZ3ltY29nZnFuYWJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NTk3OTMsImV4cCI6MjA2NjMzNTc5M30.fKtl1sR99Gff4GV1wQGBZo_x9gBQw_o7w3gv97dFnYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);